language: node_js
node_js: 7

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install -g gulp

script:
  - gulp build

after_script:
  - cd public
  - git init
  - git config user.name "KDF5000"
  - git config user.email "kdf5000@163.com"
  - git add .
  - git commit -m "Update blog"
  - git push --force "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master
  
branches:
  only:
    - master

env:
  global:
      - GIT_PAGE_REF: github.com/KDF5000/kdf5000.github.io.git
      - GH_TOKEN: 029def9c5760531df97c8143b7d11b73090da770

notifications:
  email:
    - kdf5000@163.com

  on_success: change
  on_failure: always
